#!/bin/sh

#aipc_util -w -d 0xb8005200 -W 0xf0000000
#aipc_util -w -d 0xb8005210 -W 0xf0000000
#aipc_util -w -d 0xb8005220 -W 0xf0000000
#aipc_util -w -d 0xb8005230 -W 0xf0000000
#aipc_util -w -d 0xb8005240 -W 0xf0000000
#aipc_util -w -d 0xb8005250 -W 0xf0000000
#aipc_util -w -d 0xb8005260 -W 0xf0000000
#aipc_util -w -d 0xb8005270 -W 0xf0000000
#aipc_util -w -d 0xb8005280 -W 0xf0000000
#aipc_util -w -d 0xb8005290 -W 0xf0000000
#aipc_util -w -d 0xb80052a0 -W 0xf0000000
#aipc_util -w -d 0xb80052b0 -W 0xf0000000

#aipc_util -r -d 0xb8004100 -l 0x80

#aipc_util -B
aipc_util -e

#aipc_util -r -d 0xb8004100 -l 0x80

aipc_util -w -d 0xb0000400  -i /image/dsp.img 

#sleep 20
#sleep 10

aipc_util -b

if [ -x "/bin/wait_dsp" ]; then
	wait_dsp
else
	echo "no wait_dsp, so force to sleep 5 seconds..."
	sleep 5
fi

#aipc_util -r -d 0xb8004100 -l 0x20


#aipc_util -r -d 0xb8000108 -l 0x80
#aipc_util -w -d 0xb8000108 -W 0x00560000
#aipc_util -r -d 0xb8000108 -l 0x80

#aipc_util -M 0x0

mkdir /tmp/VoIP_DSP_info
cat /proc/aipc_dev/dsp/log/contents  | grep -i "RTK VoIP Version" > /tmp/VoIP_DSP_info/VoIP_DSP_Version
cat /proc/aipc_dev/dsp/log/contents  > /tmp/VoIP_DSP_info/VoIP_DSP_Boot
